export type Category="All"|"Beds"|"Sofas"|"Dining"|"Storage"|"Accents";
export type Product={id:string;name:string;category:Exclude<Category,"All">;price:number;regular:number;size:string;material:string;finish:string;tag:string;image:string;description:string;features:string[];source:string};
const asset=(name:string)=>`https://kinwud.com/static/img/${name}?v=21789202369`;
export const products:Product[]=[
{id:"solace",name:"Solace King Bed",category:"Beds",price:0,regular:0,size:"King",material:"Engineered wood",finish:"Espresso walnut + brass",tag:"Richa / Kinwud",image:asset("bed-king-chevron-upholstered-headboard.jpg"),description:"Espresso walnut king bed with a chevron upholstered headboard and brass detailing.",features:["King bed","Espresso walnut","Brass detail"],source:"Public Kinwud catalogue"},
{id:"cascade",name:"Cascade King Storage Bed",category:"Beds",price:0,regular:0,size:"King",material:"Engineered wood",finish:"Espresso walnut & ivory oak",tag:"Richa / Kinwud",image:asset("bed-king-storage-ivory-panel.jpg"),description:"Storage bed in espresso walnut and ivory oak laminate.",features:["King storage","Ivory oak panel","Walnut finish"],source:"Public Kinwud catalogue"},
{id:"rivena",name:"Rivena King Storage Bed",category:"Beds",price:0,regular:0,size:"King",material:"Engineered wood",finish:"Espresso walnut & ivory oak",tag:"Richa / Kinwud",image:asset("bed-king-storage-slat-headboard.jpg"),description:"King storage bed with a slatted headboard and warm walnut-and-ivory finish.",features:["King storage","Slat headboard","Walnut + ivory"],source:"Public Kinwud catalogue"},
{id:"marisol",name:"Marisol U-Sectional",category:"Sofas",price:0,regular:0,size:"U-sectional",material:"Upholstered frame",finish:"Teal crushed velvet",tag:"Richa / Kinwud",image:asset("sofa-sectional-teal-velvet.jpg"),description:"A U-sectional upholstered in teal crushed velvet with polished chrome legs.",features:["U-sectional","Teal velvet","Chrome legs"],source:"Public Kinwud catalogue"},
{id:"aurelia",name:"Aurelia Curved Sectional",category:"Sofas",price:0,regular:0,size:"Sectional",material:"Upholstered frame",finish:"Champagne printed fabric",tag:"Richa / Kinwud",image:asset("sofa-sectional-beige-tufted.jpg"),description:"A curved sectional with champagne printed fabric and a soft sculptural silhouette.",features:["Curved profile","Champagne fabric","Deep seating"],source:"Public Kinwud catalogue"},
{id:"colonna",name:"Colonna 3+1+1 Sofa Set",category:"Sofas",price:0,regular:0,size:"3+1+1",material:"Upholstered frame",finish:"Mocha suede + espresso lacquer",tag:"Richa / Kinwud",image:asset("sofa-set-3-1-1-channel-tufted-mocha.jpg"),description:"Mocha suede 3+1+1 sofa set with channel tufting and espresso lacquer.",features:["3+1+1 set","Mocha suede","Channel tufting"],source:"Public Kinwud catalogue"},
{id:"lyra",name:"Lyra Dining Set",category:"Dining",price:0,regular:0,size:"6 seater",material:"Timber + upholstered seating",finish:"Honey teak + grey upholstery",tag:"Richa / Kinwud",image:asset("dining-set-6-seater-marble-scroll-chairs.jpg"),description:"Six-seater dining set in honey teak polish with grey upholstered seating.",features:["6 seater","Honey teak","Grey upholstery"],source:"Public Kinwud catalogue"},
{id:"verona",name:"Verona Dining Set",category:"Dining",price:0,regular:0,size:"6 seater",material:"Timber + upholstered seating",finish:"Honey teak + grey upholstery",tag:"Richa / Kinwud",image:asset("dining-set-6-seater-marble-slat-chairs.jpg"),description:"Six-seater dining setting with honey teak polish and grey upholstery.",features:["6 seater","Honey teak","Grey upholstery"],source:"Public Kinwud catalogue"},
{id:"elara",name:"Elara Dresser with Mirror",category:"Storage",price:0,regular:0,size:"Dresser",material:"Engineered wood + mirror",finish:"Espresso rosewood",tag:"Richa / Kinwud",image:asset("dresser-tall-mirror-espresso.jpg"),description:"Tall dresser with mirror in espresso rosewood.",features:["Tall mirror","Dresser storage","Espresso rosewood"],source:"Public Kinwud catalogue"},
{id:"lumen",name:"Lumen Dressing Table",category:"Storage",price:0,regular:0,size:"Dressing table",material:"Engineered wood + mirror",finish:"Wenge & ivory oak",tag:"Richa / Kinwud",image:asset("dressing-table-mirror-walnut.jpg"),description:"Dressing table with mirror in wenge and ivory oak.",features:["Mirror","Dressing storage","Wenge + ivory oak"],source:"Public Kinwud catalogue"},
{id:"onyx",name:"Onyx Sideboard",category:"Storage",price:0,regular:0,size:"Sideboard",material:"Rosewood + glass",finish:"Rosewood & onyx glass",tag:"Richa / Kinwud",image:asset("sideboard-rosewood-black-glass.jpg"),description:"Statement sideboard combining rosewood with dark onyx glass.",features:["Sideboard","Rosewood","Onyx glass"],source:"Public Kinwud catalogue"},
{id:"scholar",name:"Scholar Study Desk",category:"Storage",price:0,regular:0,size:"Study desk",material:"Engineered wood",finish:"Walnut & ivory oak",tag:"Richa / Kinwud",image:asset("study-desk-hutch-walnut.jpg"),description:"Study desk with hutch in walnut and ivory oak.",features:["Study desk","Hutch","Walnut + ivory oak"],source:"Public Kinwud catalogue"},
{id:"coronet",name:"Coronet Accent Chair",category:"Accents",price:0,regular:0,size:"Accent chair",material:"Upholstery + wood",finish:"Mocha suede + walnut",tag:"Richa / Kinwud",image:asset("accent-chair-carved-crown-mocha.jpg"),description:"Carved accent chair in mocha suede with walnut polish.",features:["Accent chair","Mocha suede","Walnut polish"],source:"Public Kinwud catalogue"}
];
export const categories:Category[]=["All","Beds","Sofas","Dining","Storage","Accents"];
export const finishes=[{name:"Espresso Walnut",value:"#4a3529"},{name:"Ivory Oak",value:"#d9c8a8"},{name:"Honey Teak",value:"#9a6a42"},{name:"Mocha",value:"#6a5042"},{name:"Teal Velvet",value:"#356b68"},{name:"Champagne",value:"#c5ae92"}];
export const showroom={name:"Richa Furniture",address:"Sunita Heights, Supriya Cinema Road, Mirza Tola Road, Bettiah, Bihar 845438",phone:"+91 88779 27486",hours:"10:00 — 20:00 daily",maps:"Richa Furniture, Sunita Heights, Supriya Cinema Road, Bettiah, Bihar 845438",storeImage:asset("store-img/richa-furniture-bettiah.jpg"),source:"Public Kinwud / Richa catalogue"};
