export type Category="All"|"Beds"|"Sofas"|"Dining"|"Storage"|"Accents";
export type Product={id:string;name:string;category:Exclude<Category,"All">;price:number;regular:number;size:string;material:string;finish:string;tag:string;image:string;description:string;features:string[]};
const u=(id:string)=>`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1400&q=82`;
export const products:Product[]=[
{id:"meridian",name:"Meridian King Bed",category:"Beds",price:33200,regular:36900,size:'78" × 72"',material:"Engineered wood",finish:"Walnut",tag:"SIGNATURE",image:u("1616486338812-3dadae4b4ace"),description:"A calm, architectural king bed designed to anchor a bedroom without overwhelming it.",features:["King size","Storage-ready","Upholstered headboard"]},
{id:"havelock",name:"Havelock Corner Sectional",category:"Sofas",price:70900,regular:83500,size:'112" × 88"',material:"Kiln-dried frame",finish:"Warm Taupe",tag:"SIGNATURE",image:u("1555041469-a586c61ea9bc"),description:"A deep corner sectional with a generous footprint for evenings that run long.",features:["Corner layout","Ottoman + stools","Deep seating"]},
{id:"heritage",name:"Heritage Dining Set",category:"Dining",price:62500,regular:69500,size:'60" × 36"',material:"Teak + marble",finish:"Natural Teak",tag:"CLASSIC",image:u("1617806118233-18e1de247200"),description:"A six-seater dining setting that brings warm timber and stone together.",features:["6 seater","Marble top","Teak chairs"]},
{id:"fortis",name:"Fortis 3-Door Wardrobe",category:"Storage",price:19300,regular:21500,size:'54" × 78" × 21"',material:"Engineered wood",finish:"Deep Walnut",tag:"BESTSELLER",image:u("1616486338812-3dadae4b4ace"),description:"Full-height storage with a continuous walnut look, mirror and practical interior.",features:["3 doors","Internal mirror","Hanging rail"]},
{id:"elara",name:"Elara Dresser with Mirror",category:"Storage",price:18000,regular:20500,size:'36" × 80" × 18"',material:"Engineered wood + mirror",finish:"Espresso Rosewood",tag:"DETAIL",image:u("1618221195710-dd6b41faaea6"),description:"A full-length mirror, display bay and drawer bank in one compact vertical piece.",features:["Bevelled mirror","4 drawers","Warm LED canopy"]},
{id:"lumen",name:"Lumen Dressing Table",category:"Storage",price:7200,regular:8500,size:'34" × 76" × 17"',material:"Engineered wood + mirror",finish:"Wenge & Ivory Oak",tag:"NEW",image:u("1616486338812-3dadae4b4ace"),description:"A compact dressing zone with lighting, lockable mirror storage and soft-close drawers.",features:["Twin spotlights","Lockable mirror","2 drawers"]},
{id:"onyx",name:"Onyx Sideboard",category:"Storage",price:13000,regular:14500,size:'54" × 32" × 18"',material:"Rosewood + glass",finish:"Rosewood & Onyx",tag:"STATEMENT",image:u("1615873968403-89e068629265"),description:"A dark glass and rosewood sideboard built to read as a statement console.",features:["Glass fronts","Solid rosewood detail","Adjustable feet"]},
{id:"scholar",name:"Scholar Study Desk",category:"Storage",price:7200,regular:8500,size:'48" × 52" × 20"',material:"Engineered wood",finish:"Walnut & Ivory Oak",tag:"FAMILY",image:u("1497366754035-f200968a6e72"),description:"A study setup designed to grow with a child's room, with a removable hutch.",features:["Removable hutch","3-door tower","25 mm desktop"]},
{id:"coronet",name:"Coronet Accent Chair",category:"Accents",price:9400,regular:10500,size:'28" × 30" × 44"',material:"Upholstery + wood",finish:"Clay",tag:"ACCENT",image:u("1598300042247-d088f8ab3a91"),description:"A compact reading-chair silhouette for the corner that deserves a little more character.",features:["Accent seating","Compact footprint","Soft upholstery"]}
];
export const categories:Category[]=["All","Beds","Sofas","Dining","Storage","Accents"];
export const finishes=[{name:"Walnut",value:"#5d4636"},{name:"Ivory Oak",value:"#d8c7aa"},{name:"Espresso",value:"#2f2521"},{name:"Natural Teak",value:"#9b6c45"},{name:"Clay",value:"#a96854"},{name:"Sage",value:"#737865"}];
export const showroom={name:"Richa Furniture",address:"Sunita Heights, Supriya Cinema Road, Mirza Tola Road, Bettiah, Bihar 845438",phone:"+91 88779 27486",hours:"Mon — Sun · 10:00 — 20:00",maps:"Richa Furniture, Sunita Heights, Supriya Cinema Road, Bettiah, Bihar 845438"};
